### PR TITLE
Refactor MetricsService to own interface

### PR DESCRIPTION
**Pull request by andymc12**
- refactored MetricRegistry into it's own service (from LookupService)
- req'd changes in CDI implementation module and impl
- new test cases

These changes should make it easier for containers (like Open Liberty) to separate out the Metrics implementation.

### CODE REVIEW

**Comment by ybroeker** [comment]
tried something similar in https://github.com/ybroeker/smallrye-graphql/tree/feat/opentracing, mainly to use other metrics-versions (unfortunately we have to use an older version) and to connect OpenTracing/OpenTelemetry.

Maybe there is a way to merge them?

**Comment by phillip-kruger** [comment]
Thanks @andymc12 !

**Comment by phillip-kruger** [comment]
@ybroeker - we should be able to follow the same pattern for tracing, so have a Tracing service interface ?

**Comment by phillip-kruger** [comment]
Thanks @andymc12 !

**Pull request merged**
