### PR TITLE
Use fields and methods from superclasses while creating types

### PR DESCRIPTION
**Pull request by ybroeker**
Currently, all fields from superclasses are ignored while creating input-types and only the first superclass is considered while creating output-types.

With this PR, all fields and methods from a class and its parents are used.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Thanks @ybroeker - same comment as before, adding a ticket and even better a PR as well to the spec would be great !

Thanks

**Comment by ybroeker** [comment]
Thanks for merging! Added testcases in eclipse/microprofile-graphql#215

**Comment by phillip-kruger** [comment]
Thanks @ybroeker !

**Comment by phillip-kruger** [comment]
Hi @ybroeker . If I test against the MicroProfile GraphQL 1.1-Snapshot I still fail ?!?
I have documented how you can run against the SNAPSHOT version in the README. 
Can you have a look ?

```
87 [SubTypes] (9) - Expecting non-null field from parent in OutputType expected [true] but found [false]
```

**Comment by ybroeker** [comment]
That's the bug fixed in smallrye/smallrye-graphql#114. 

Followed the suggestion from @andymc12 in eclipse/microprofile-graphql#215 and added `@Name` to a field, which exposed this bug.

**Pull request merged**
