### PR TITLE
Issue/2068

### PR DESCRIPTION
**Pull request by robp94**

### CODE REVIEW

**Comment by mskacelik** [comment]
I tried to play around with the new implementation in the given reproducer, and it seems that everything works as it should. +1

**Review by mskacelik — APPROVED** [review]

**Comment by jmartisk** [comment]
Thanks @robp94  and  @mskacelik !!

**Comment by mskacelik** [comment]
Out of curiosity, does the federation require the interface and its implementors to have the same key identifier?

**Comment by robp94** [comment]
> Out of curiosity, does the federation require the interface and its implementors to have the same key identifier?

We use it that way, but I never tried it with different keys.

**Comment by robp94** [comment]
@jmartisk could we get this in quarkus 3.12.0?

**Comment by jmartisk** [comment]
@robp94 Sorry, there are some issues with the release pipeline that need fixing first, and 3.12 is already in CR so it's probably too late (the changes in smallrye-graphql 2.9 will be quite big) so I'm rather targeting 3.13 now

**Pull request merged**
