### PR TITLE
#752: allow formatting of Instant return types; format Instant as ISO_INSTANT

### PR DESCRIPTION
**Pull request by t1**

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Failure in the TCK. Please fix :)

**Comment by t1** [comment]
Jeah, I'm on it. I didn't expect that times have time zones ;-)

**Comment by phillip-kruger** [comment]
Still failing ....

**Comment by t1** [comment]
I know, I know ;-)

**Comment by t1** [comment]
Now it should work, but it fails because it had problems downloading the internet again. I understand that there the maven build files are predefined by RedHat, but here's what I do to cache the artifacts:

```yaml
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
```

Otherwise: could you restart the builds?

**Comment by t1** [comment]
BTW: It would be great to get a release with this soon...ish :-)

**Pull request merged**
