### PR TITLE
Defensively decoding graphql errors

### PR DESCRIPTION
**Pull request by cherrydev**
This is to address #1349
While the error checking might seem excessive, because the code in question is error handling code that it should make every effort to be as defensive as is practical.

### CODE REVIEW

**Comment by cherrydev** [comment]
Please note that the failing tests were failing before I got to it (and are unrelated)

**Comment by jmartisk** [comment]
Can you please rebase and run a full Maven build to have the formatter plugin fix the formatting? And then push again.. I'd do that for you but seems I don't have a permission to write into your branch. Thanks

**Comment by cherrydev** [comment]
@jmartisk Done!

**Review by jmartisk — APPROVED** [review]
Quarkus failures are unrelated, wildfly failures are because you introduced usage of `org.jboss.logging` in the client/implementation module, that will need a minor update on the WildFly side to fix the class loading, I'll take care of that.

Thanks!!

**Pull request merged**
