### PR TITLE
added a check that throws an exception if a field name and source field name are the same

### PR DESCRIPTION
**Pull request by mskacelik**
/cc @jmartisk 
fixes: #2064 

+ added a check for exception message in one of the previous tests

Also note that this is a breaking change.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Awesome !! Thanks @mskacelik !

**Comment by mskacelik** [comment]
It seems that one of the Quarkus tests is failing now (CompletionStageTest), because of the duplicated field name *authors* (one as a field and one as a source batching field). Gonna fix it now.

**Comment by mskacelik** [comment]
quarkus changes: https://github.com/mskacelik/quarkus/tree/srgql-2.8.2
exact commit: https://github.com/quarkusio/quarkus/commit/7d5709e96961d3ead3f8467cbfe6caf5a9759eb9

**Review by phillip-kruger — APPROVED** [review]
LGTM

**Review by jmartisk — APPROVED** [review]

**Pull request merged**
