### PR TITLE
Added two more options when including dependencies in the maven plugin

### PR DESCRIPTION
**Pull request by phillip-kruger**
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

@marceloverdijk - maybe we want to do this in the gradle plugin as well ? Not sure.

### CODE REVIEW

**Comment by marceloverdijk** [comment]
@phillip-kruger Yes I will add something similar for the Gradle plugin.
In Gradle terms this will be something like `includeDependenciesConfigurations`. I will create a PR this evening.

**Comment by phillip-kruger** [comment]
THanks @jmartisk. Thanks @marceloverdijk .

**Comment by marceloverdijk** [comment]
@phillip-kruger I looked into adding these options to the Gradle plugin as well, but it is not that easy. In Gradle it seems difficult to get all dependencies for a certain scope/configuration with a handle to the actual file.
I will continue, but it will take a bit more time unfortunately.

**Comment by phillip-kruger** [comment]
No worries :) I just wanted to make sure you know. We can create an issue and do this later

**Comment by marceloverdijk** [comment]
I think I found a solution and work it out this this evening.

But probably I will also add another option `includeDependenciesRecursive` (or  `includeDependenciesTransitive`) so only direct specified dependencies will be index (and not the transitive ones). Maybe good to add to the Maven plugin as well ;-)

**Comment by phillip-kruger** [comment]
Sounds good ! Thanks :)

**Comment by marceloverdijk** [comment]
In Gradle this will provide a nice option to do:

```
configurations {
    schema // we add a custom configuration
}

dependencies {
    implementation "foo:bar:1.0"
    implementation "com:example-with-types-to-be-indexed:1.0"
    schema "com:example-with-types-to-be-indexed:1.0"
}

```

and then generate the schema something like 
```
./gradlew generateSchema --include-dependencies 
            --include-dependencies-configrations=schema 
            --include-dependencies-transitive=false 
```

**Comment by marceloverdijk** [comment]
Creates https://github.com/smallrye/smallrye-graphql/pull/211 for the additional Gradle options + a bit of refactoring.

**Pull request merged**
