### PR TITLE
Fix potential ConcurrentModificationException

### PR DESCRIPTION
**Pull request by geoand**
Fixes: https://github.com/quarkusio/quarkus/issues/24996

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Thanks @geoand !

**Comment by geoand** [comment]
YW

**Review by jmartisk — APPROVED** [review]

**Comment by gsmet** [comment]
@jmartisk I think we would need a fix for 2.8.2, it looks quite bad. Thanks!

**Comment by jmartisk** [comment]
@gsmet Yeah I will get a SmallRye GraphQL 1.4.5 out

**Comment by gsmet** [comment]
Thanks!

**Pull request merged**
