### PR TITLE
Fix for federation data fetcher correct support namespaces

### PR DESCRIPTION
**Pull request by RoMiRoSSaN**
Fix for federation data fetcher correct support namespaces
See #2173

### CODE REVIEW

**Comment by jmartisk** [comment]
Would it be possible to add some kind of test that verifies this?

**Comment by RoMiRoSSaN** [comment]
@jmartisk ok, i think i will do it

**Comment by RoMiRoSSaN** [comment]
@jmartisk please, check it.

**Review by jmartisk — APPROVED** [review]

**Comment by jmartisk** [comment]
Thanks!

**Pull request merged**
