### PR TITLE
move MavenConfig to be a standalone facade

### PR DESCRIPTION
**Pull request by shmulik-klein**
This PR is a hacky solution for #963

### CODE REVIEW

**Review by jmartisk — APPROVED** [review]

**Comment by jmartisk** [comment]
I tested this manually and it looks good to me. Let's have @phillip-kruger have a brief look too, as he knows more about the recent config changes

I'll also think about how to add some automated test coverage, that would be really handy

**Comment by shmulik-klein** [comment]
Thanks @jmartisk!

I'm not much familiar with Maven's plugins framework and its testing capabilities, but maybe just invoking the plugin by a unit test can be sufficient.

**Comment by t1** [comment]
I wrote a Maven plugin ages ago and can't remember the details, but there is explicit testing support in Maven... and I bet also in Gradle.

**Comment by phillip-kruger** [comment]
@t1 are you volunteering ? :)

**Review by phillip-kruger — APPROVED** [review]
Thanks ! We can potentially expose more options in the maven config

**Comment by jmartisk** [comment]
I reported https://github.com/smallrye/smallrye-graphql/issues/966 and plan to look into it

**Pull request merged**
