### PR TITLE
Micro profile config fix

### PR DESCRIPTION
**Pull request by pfaul**
Hello,

I fixed the usage of Optionals in MicroProfileConfig.

See issue: https://github.com/smallrye/smallrye-graphql/issues/1756

Best regards,
Paul

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Thanks @pfaul - I'll have a look. Can you look at the CI failure?

**Comment by jmartisk** [comment]
CI is failing because of code formatting. Please run a new Maven build to have the formatter plugin do its job, and push after that

**Comment by pfaul** [comment]
I see. Consider it done :)

**Comment by jmartisk** [comment]
It's still complaining that imports are not sorted :) perhaps your IDE re-arranged them after you ran the build, you might need to turn that off in your IDE

**Comment by pfaul** [comment]
Alright, sorry for the confusion. Now imports and formatting should be correct :)

**Comment by jmartisk** [comment]
Ok the code with this looks cleaner and a bit more correct, so why not. Could you please squash it into one commit? 19 commits for such a minor change is really too many

**Comment by pfaul** [comment]
You can also just squash the commits during the merge ;)

**Comment by jmartisk** [comment]
Ok... I generally prefer to avoid directly messing with other people's work :) but fine.

**Review by jmartisk — APPROVED** [review]

**Comment by jmartisk** [comment]
Merged, thanks!

**Comment by pfaul** [comment]
Cool, thank you too :)

**Comment by phillip-kruger** [comment]
Thanks @pfaul !

**Pull request merged**
