### PR TITLE
fix #946: prevent json-path-exception

### LINKED ISSUE #946: Typesafe Client: JsonException when a GraphQL error has a path that is actually `null`
```json
{
  "errors": [
    {
      "message": "some error message",
      "locations": [{"line": 1, "column": 256}],
      "path": ["foo", "bar", "baz"],
    }
  ],
  "data": {
    "foo": [
      {
        "bar": null,
      }
    ]
  }
}
```

There was an error in `foo/bar/baz` that resulted in `foo/bar` being `null`.

⇒ The typesafe client fails with `javax.json.JsonException: The reference value in a JSON Pointer must be a JSON Object or a JSON Array, was 'NULL'` in `ResultBuilder` line 74 when trying to apply an `ErrorOr`.

Expected: don't apply the `ErrorOr`

### PR DESCRIPTION
**Pull request by t1**

### CODE REVIEW

**Comment by t1** [comment]
I have no idea why these suddenly fail... I haven't changed anything about the webjars, have I?

**Comment by jmartisk** [comment]
> I have no idea why these suddenly fail... I haven't changed anything about the webjars, have I?

Something must be wrong in the online Maven repo, I suddenly can't build even the `main` branch

**Comment by jmartisk** [comment]
It must have something to do with graphiql 1.4.2 release that happened today (or maybe is still happening): https://repo.maven.apache.org/maven2/org/webjars/npm/graphiql/1.4.2/ 
But even updating to 1.4.2 doesn't fix the build for me. This is very, very unfortunate that our build can be broken by something like this

**Comment by phillip-kruger** [comment]
I is that what you are talking about. Ok I am busy fixing that :)

**Comment by phillip-kruger** [comment]
https://github.com/smallrye/smallrye-graphql/pull/952 should fix that

**Comment by phillip-kruger** [comment]
@jmartisk @t1 I want to do a release. Can we get this in there ? Is there anything else you are working on that I should wait for ?

**Comment by t1** [comment]
I'm currently not working on any other issues. You can go ahead.

**Comment by jmartisk** [comment]
Nothing from my side.
I'll quickly have a look at this in a bit, now that the build is fixed

**Comment by phillip-kruger** [comment]
@jmartisk Build fixed, merge if you are happy, then I'll do the release.

**Comment by jmartisk** [comment]
Cool, I'll need that for WF that got broken by the graphql-java upgrade.
Please go ahead

**Review by jmartisk — APPROVED** [review]

**Pull request merged**
