### PR TITLE
fix #299: custom GraphQL error `extension` fields

### LINKED ISSUE #299: Add generic ability to add extension key-value for Errors
Relate to #282. We have code as a key supported with #295 but still need a generic key value.

Some more features:

- Move the knowledge to the model, so that we do not need to check annotations in runtime.
- Allow adding of Annotation on method that throw the exception, to get per instance usage (currently it's global)
- Add way to do all that is done for code for any other key-value

### PR DESCRIPTION
**Pull request by t1**
Add `ErrorExtensionProvider` via `ServiceLoader` and use it for `code` and `exception` (class name)

### CODE REVIEW

**Comment by jmartisk** [comment]
Are you be willing to add a short example of how to use this into the documentation adoc files?

Also, @phillip-kruger after the experience with having to branch out 1.4.3, I think this should go into 1.6.0 rather than 1.5.1 (or maybe we won't plan a 1.6.0 at all, and just keep this in `main` for 2.0, without backporting at all) - WDYT?

**Review by phillip-kruger — APPROVED** [review]
LGTM, this does not look like a breaking change ? Or am I missing something ?

**Comment by jmartisk** [comment]
Not breaking, but a new public API feature. With semantic versioning, new features mean a minor version bump (https://semver.org/#spec-item-7).

**Comment by phillip-kruger** [comment]
a, ok gotcha. Yes then probably 2.0.0 and 1.6.0

**Comment by jmartisk** [comment]
I've created a 1.6.x branch and sent a PR (https://github.com/smallrye/smallrye-graphql/pull/1400) backporting this one, so that we can properly run the CI (Quarkus and WildFly CI jobs are broken with main because main has already migrated to the jakarta namespace.... 1.6 branch should work with Quarkus and WF)

**Review by jmartisk — APPROVED** [review]

**Pull request merged**
