### PR TITLE
fix config injection of optional black/whitelist

### PR DESCRIPTION
**Pull request by t1**
When I start `smallrye-graphql` in a WildFly 19, it logs the following warning:

```[io.smallrye.graphql.execution.error.ExceptionLists] (default task-1) Could not create instance of exception class [[]]. Can not do transitive black/whitelist check for this class```

I found that in `GraphQLConfig` the default for the black/whitelist is `[]`, which obviously doesn't work as expected: it creates a list containing the string `"[]"`. So I changed it to an `Optional<List<String>>` instead and it works just fine.

### CODE REVIEW

**Comment by t1** [comment]
Just saw that the TCK fails now... I'm checking.

**Comment by phillip-kruger** [comment]
Awesome ! I also seen that in Quarkus. Would be awesome if you can fix that ! Let me know if I can help with the TCK

**Comment by t1** [comment]
Even on the upstream master, I also get several failures on my machine... due to localization issues, obviously (that's why I skipped the tests before). I guess I'll have to fix them first :-/

**Comment by phillip-kruger** [comment]
Yea, switch to JDK 8, I am busy fixing the locale issues on 11 as we speak

**Comment by phillip-kruger** [comment]
Great ! Thanks very much !! Merging now

**Comment by t1** [comment]
noooo... you where too quick... it still doesn't work :-(

**Comment by phillip-kruger** [comment]
Ha ha. Ok i'll revert

**Comment by t1** [comment]
Sorry... I shouldn't have pushed it ;-) I'll create a new PR

**Comment by phillip-kruger** [comment]
No worries, yes please create a new PR. You might have to sync your fork

**Pull request merged**
