### PR TITLE
#1140 Enum vulnerable to injection attack

### PR DESCRIPTION
**Pull request by cherrydev**
Simple fix to make sure that Enum values are valid according to spec, which also makes injection attacks impossible

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
Thanks ! @t1 or @jmartisk also please review

**Comment by jmartisk** [comment]
Code changes look good to me. It made me realize that we don't have any client tests for enums, so I'm adding that to my TODO list.

Could you run a Maven build to have the formatter plugin reformat the code and then commit again?

**Comment by cherrydev** [comment]
@jmartisk There ya go!

**Review by t1 — DISMISSED** [review]
LGTM

**Comment by phillip-kruger** [comment]
CI still failing. You need to do a full build locally and commit & push again.

**Comment by cherrydev** [comment]
I cannot successfully do a full build, so I just ran the `formatter:format` goal. When I attempt to do a I build I get the error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:unpack (default) on project smallrye-graphql-runner: Unable to find/resolve artifact.: Could not find artifact io.smallrye:smallrye-graphql-tck:jar:tests:1.4.0-SNAPSHOT -> [Help 1]
```

I'm running maven 3.8.1 with the command line: `mvn clean compile`
I have manually run the `impsort:sort` goal which hopefully will satisfy.

**Review by jmartisk — APPROVED** [review]
LGTM.

Please use `mvn clean install` instead of `mvn clean compile` for now, we have subtleties in our build that make it fail if you only run `compile` (the `runner` module depends on tests produced by the `tck` module, but if you run only `compile`, then that artifact is not produced). I'll try to figure out if this can be fixed.

**Comment by jmartisk** [comment]
Merged, thanks for your contribution!

**Comment by jmartisk** [comment]
Btw. https://github.com/smallrye/smallrye-graphql/pull/1145 should fix the build problem (I hope)

**Pull request merged**
