### PR TITLE
Issue 1753 and Issue 1950

### PR DESCRIPTION
**Pull request by debu999**
Fix to provide custom serializer and deserialzer for Smallrye-graphql jsonb config.

Issues #1753  and Issues #1950 

@jmartisk @phillip-kruger 

This is my first contribution, so need your advise on the change. I have added few changes to make the JSONB Config exposed out. 

Can you have a look at it and share your feedback. Moreover need some help in testcases if those have to be added.

```
# Usage for custom changes will be exclusive to smallrye-graphql viz. no ObjectID dependency.
JsonBCreator.setJsonB(Collections.singletonList(OBJECTID_SERIALIZER),
        Collections.singletonList(OBJECTID_DESERIALIZER));
```

### CODE REVIEW

**Comment by debu999** [comment]
Screenshot 2024-01-14 at 3 09 12 PM
Screenshot 2024-01-14 at 3 09 20 PM

**Comment by jmartisk** [comment]
So, if I understand this correctly, the goal is to allow users to call `JsonBCreator.setJsonB(...)` to register their own serializers and this should happen at application startup?

I would be super happy if you could also

- Add a few lines about this into the documentation (a page similar to https://github.com/smallrye/smallrye-graphql/blob/main/docs/custom-json-deserializers.md, but for serializers)
- Add a test that demonstrates this (under https://github.com/smallrye/smallrye-graphql/tree/main/server/integration-tests/src/test/java/io/smallrye/graphql/tests)

**Comment by jmartisk** [comment]
CI is complaining that the code is not formatted, please run a full maven build and commit+push afterwards, the formatter plugin will take care of it

**Comment by jmartisk** [comment]
By the way, is there some reason why we shouldn't make it the same as for deserializers, that is in a method of `EventingService`, like it's described in https://github.com/smallrye/smallrye-graphql/blob/main/docs/custom-json-deserializers.md? With the current implementation, it's not completely clear when/how one should call `JsonBCreator.setJsonB`, so I think it would be nicer. `JsonBCreator` class wasn't meant to be public API.

**Comment by debu999** [comment]
@jmartisk I was just trying to make it work  let me check the eventing service

**Comment by jmartisk** [comment]
Thanks! :)

**Comment by debu999** [comment]
@jmartisk I did validate seems only one liner change was needed in ArgumentHelper class. I have updated the documentation as well to reflect the same. Do you think we are good to merge now. Or we need to add documentation like 
```
@Override
    public Map<String, Jsonb> overrideJsonbConfig() {
        JsonbConfig config = new JsonbConfig().withDeserializers(OBJECTID_DESERIALIZER).withSerializers(
            OBJECTID_SERIALIZER);
        return Collections.singletonMap(ReactivePerson.class.getName(), JsonbBuilder.create(config));
    }
```

**Comment by debu999** [comment]
Only change needed was `    String jsonString = JsonBCreator.getJsonB(className).toJson(m);`

**Comment by jmartisk** [comment]
@chokme Can you confirm this solves your issue?

**Comment by jmartisk** [comment]
@debu999, sure, we can have DEBUG-level logs for that!

**Comment by debu999** [comment]
Will commit and push the changes in sometime. @jmartisk

**Comment by jmartisk** [comment]
I've reformatted the code and changed the debug log a bit, let's see

**Review by jmartisk — APPROVED** [review]
Thanks!

**Pull request merged**
