### PR TITLE
Fix randomly failing SubscriptionHasToBeCancelledOnWebSocketCloseTestCase

### PR DESCRIPTION
**Pull request by acanda**
SubscriptionHasToBeCancelledOnWebSocketCloseTestCase was randomly failing on my machine because the hard-coded sleeps were not long enough. I replaced the sleeps with awaits that wait until the things the test expects actually happen or fail when it takes too long.

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM, Thanks !

**Comment by phillip-kruger** [comment]
@jmartisk the WF build fails with noclassdeffound. Can you check ?

**Comment by jmartisk** [comment]
@phillip-kruger that's expected because wildfly hasn't upgraded to jandex 3 yet

**Comment by phillip-kruger** [comment]
Ok cool, thanks

**Pull request merged**
