### PR TITLE
Start work on wildcard type support.

### PR DESCRIPTION
**Pull request by nenros**
I added simply try to handle wildcard type. But i'm not able to write unit test for that. I tried to write one but it pass without my code so probably it wasn't best.

I would like to have wildcard support to make kotlin coroutines work in the future.

So i would be gratefull for help and comments ;)

### CODE REVIEW

**Comment by nenros** [comment]
So I need some help with working test, that would really test something.

**Comment by phillip-kruger** [comment]
@nenros - Thanks for this. When do you get the error mentioned above ?

**Comment by phillip-kruger** [comment]
What happened here ?

**Comment by nenros** [comment]
Maybe i will try write once again, i'm not sure is that PR still valid after all changes.

**Pull request closed without merging**
