### PR TITLE
Try to fix gradle

### PR DESCRIPTION
**Pull request by phillip-kruger**
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by phillip-kruger** [comment]
@marceloverdijk - please help.

**Comment by marceloverdijk** [comment]
@phillip-kruger I'm not sure this is the right direction to fix the issue to be honest.
See my comments in https://github.com/smallrye/smallrye-graphql/pull/351 which I think is the root issue of why the build started failing.

**Comment by phillip-kruger** [comment]
Yea I have no idea what I am doing. Grade is not something I know at all. Good catch on the parent pom. Should we open a new issue and continue there ?

**Comment by marceloverdijk** [comment]
Yes maybe good to create a separate issue and check about the parent Pom. Maybe we can reconfigure the compiler plug-in in the gradle-plugin module to not compile the sources..

**Pull request closed without merging**
