### PR TITLE
#521: initial GraphQL Federation extension

### PR DESCRIPTION
**Pull request by t1**

### CODE REVIEW

**Comment by phillip-kruger** [comment]
You have SNAPSHOT dependencies. Do we need a release first ? Also, why are you using the client ? Tests ?

**Comment by t1** [comment]
I've added a note that it's experimental, so maybe merging is okay. Did you get it the demo apps to run?

**Comment by phillip-kruger** [comment]
You can actually mark the annotations as `@Experimental` (from smallrye-commons) as well. Look at the annotation in the api project

**Comment by t1** [comment]
did

**Review by phillip-kruger — DISMISSED** [review]
Great !

**Comment by phillip-kruger** [comment]
Ok, stupit format thing. Just build on your laptop and push again please

**Comment by t1** [comment]
formatting again! one sec, please.

**Review by phillip-kruger — APPROVED** [review]
Thanks @t1

**Pull request merged**
