### PR TITLE
typesafe client: `@OutputOnly`

### LINKED ISSUE #522: `@NonInput`
If a java class is used an `Input` as well as a `Type`, but there are resolver methods in the GraphQL service, then some fields are returned as output but not allowed as input (see also #517). Instead of defining two separate classes with most of the fields duplicated, it would be convenient to mark some fields as `@NonInput`, so the typesafe client checks that they are actually `null` and then doesn't send them at all to the service.

### PR DESCRIPTION
**Pull request by t1**
fixes #522 and a minor bug when an error has a path to a nested field but the container value is null

### CODE REVIEW

**Review by phillip-kruger — COMMENTED** [review]
As I said in the issue, I do not think we should introduce this new annotation, but rather use `@Ignore` as on the server.

**Comment by t1** [comment]
I just non-suggestively asked the developers in my team. All 5 of them said the same thing: using `@Ignore` on the setter needs a lot of explanation and learning; a separate `@OutputOnly` is much easier to understand. We probably should think about adding this to the server, too.

**Comment by phillip-kruger** [comment]
We have discussed this and decided to align with JsonB.
See https://javaee.github.io/jsonb-spec/users-guide.html#ignoring-properties

**Comment by phillip-kruger** [comment]
@t1 - The client should also support the JsonB annotation (as the server do) `@JsonbTransient` and other JsonB annotations.

**Comment by phillip-kruger** [comment]
There are also other annotations that work this way (field = both, setter = input and getter=output). 
`@Name` , `DateFormat`, `NumberFormat` , `Description` and so on. The client should work the same way.

See for example https://download.eclipse.org/microprofile/microprofile-graphql-1.0.3/microprofile-graphql.html#naming

**Comment by t1** [comment]
@phillip-kruger : yes, you're right with everything you say. This is just not where the client currently is!

Annotating a setter as `@JsonbTransient` makes a lot of sense from the perspective of JSON-B where you think about de/serialization. But in the context of a class used as a client side GraphQL Input, it's strange to annotate a setter as `@Ignore`... there is a valid reasoning behind that, but it doesn't come naturally. A separate annotation would make things much easier to grasp.

**Comment by phillip-kruger** [comment]
@andymc12 - how does RESTClient do this ? Since JAX-RS also support JsonB annotation, does RESTClient do the same ?

@t1 - We should rather put effort into getting the client where it needs to be, than add annotations that later potentially will have to be removed.

**Comment by t1** [comment]
Let's talk about this in the next meeting

**Comment by phillip-kruger** [comment]
Would #316 solve this in another way (so you can now in your project define this an an alias ?)

**Comment by t1** [comment]
> Would #316 solve this in another way (so you can now in your project define this an an alias ?)

We would need way to move a `@OutputOnly` field-level Stereotype annotation to a `@Ignore` annotation on the setter... possible, but not here, yet.

**Comment by phillip-kruger** [comment]
Closing, as we decided to do @Ignore(on=INPUT) and this will first need some changes in MicroProfile API

**Pull request closed without merging**
