### PR TITLE
Allow `@Query` on POJO-methods, refs #704

### PR DESCRIPTION
**Pull request by ybroeker**
This PR allows to use `@Query` on POJO-methods, so methods don't need to be prefixed with `get`/`is`.

#704 should not be closed yet, native record support would still be desirable. But at least it allows to annotate components with `@Query` instead of implementing additional getters.

I'm not sure what the backport policy is, if desired I can add that to 1.0.x as well.

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Yes please backport as well
Thanks @ybroeker !

**Comment by phillip-kruger** [comment]
Hi @ybroeker, hope you are well, seems this PR broke Quarkus in native mode :( 
see  https://github.com/quarkusio/quarkus/issues/17349

I'll look at this a.s.a.p, but if you have an idea what the problem is, please share :)

**Comment by ybroeker** [comment]
Apparently MethodHandles have to be enabled via an explicit flag in Graalvm 20.3 (at least the part that is used), and full support has only been added with 21.0 (https://github.com/oracle/graal/issues/2761).

It should be easy to replace MethodHandles in `FieldDataFetcher`, they are only used to be able to access fields and methods in the same way.

Can create a pull request later

**Comment by phillip-kruger** [comment]
Great ! Thanks :)

**Pull request merged**
