### PR TITLE
Correct Uni Error handling for 1.0.x

### PR DESCRIPTION
**Pull request by Andro999b**
Backport of https://github.com/smallrye/smallrye-graphql/pull/653 for 1.0.x

### CODE REVIEW

**Comment by Andro999b** [comment]
@phillip-kruger version for 1.0 branch

**Review by phillip-kruger — APPROVED** [review]
Thanks @Andro999b  - This should be in Quarkus soon

**Comment by Andro999b** [comment]
@phillip-kruger Thanks

**Comment by Andro999b** [comment]
@phillip-kruger Is there any change that it will be released in 1.0.x any times soon? Thanks.

**Comment by phillip-kruger** [comment]
Hi, should be in the next version of Quarkus (see https://github.com/quarkusio/quarkus/wiki/Release-Planning).
I usually release here a few days before and pull the new version into Quarkus

**Pull request merged**
