### PR TITLE
Unwrap document from Context

### PR DESCRIPTION
**Pull request by computerlove**

### CODE REVIEW

**Review by phillip-kruger — DISMISSED** [review]
LGTM ! Thanks @computerlove !

**Comment by computerlove** [comment]
Got a bit confused by the formatting error...

**Comment by phillip-kruger** [comment]
CI running now, let's see :)

**Review by phillip-kruger — DISMISSED** [review]

**Comment by phillip-kruger** [comment]
Basically, you need to build on local, that should apply all formatting rules, then commit the code. Getting another formatting error :(

**Comment by computerlove** [comment]
`mvn formatter:validate impsort:check install` now runs successfully on both JDK8 and JDK11

**Comment by phillip-kruger** [comment]
Awsome ! Thanks, waiting for CI :)

**Review by phillip-kruger — APPROVED** [review]

**Comment by phillip-kruger** [comment]
Nice ! Thanks @computerlove !

**Pull request merged**
