### PR TITLE
Allow interfaces to be mapped as types or inputs

### LINKED ISSUE #926: Java interface should only be mapped to GraphQL interface if `@Interface` is annotated
Hi,

I tried to work further on the Blaze-Persistence integration with MP GraphQL but I hit another roadblock because I get the following error:

```
interface type 'SomeInterface' cannot implement 'SomeInterface' because that would result on a circular reference
```

That is because I have a query that returns the type 'SomeInterface' which is a Java interface. But why would SmallRye GraphQL even care what kind of class this is for the GraphQL schema? IMO a Java interface should be modeled as GraphQL object type unless it was annotated as `@Interface`.

I tried using SmallRye GraphQL 1.0.26.Final with Quarkus 1.13.7.Final

### PR DESCRIPTION
**Pull request by phillip-kruger**
Fix #926

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Comment by robp94** [comment]
Server. For example, the added test. https://github.com/phillip-kruger/smallrye-graphql/blob/fc3ad76f8618ca89817399a4d9273fdb83058d4e/server/tck/src/test/java/io/smallrye/graphql/test/apps/interfaces/api/FoodResource.java

**Comment by phillip-kruger** [comment]
So are you asking how you would know what the concrete class is ?

**Comment by robp94** [comment]
When I add a mutation to the linked api like this:
```
    @Mutation
    public Eatable inputEatable(Eatable eatable) {
        return eatable;
    }
```

I get the following error
`Class org.acme.Eatable is used as input, but does neither have a public default constructor nor a JsonbCreator method`

I don't see how to provide an JsonBCreator at the interface, for example, like what the concrete class is. Could you provide an example in the test, or is this not supported, and I misunderstood the pull request?

**Comment by phillip-kruger** [comment]
mmm, so the schema generate ok (that is what this PR did) but it fails at runtime ? Please open a bug, referencing this and if possible add a reproducer.

**Comment by robp94** [comment]
Quarkus fails to start.

**Pull request merged**
