### PR TITLE
JUnit 4 -> JUnit 5 Vintage

### PR DESCRIPTION
**Pull request by t1**
It still depends on smallrye-parent 19-SNAPSHOT, so it won't build on GitHub and shouldn't be merged before that was released.

### CODE REVIEW

**Comment by t1** [comment]
Should fix #100

**Comment by t1** [comment]
If I can find the time for it, I may update some tests to JUnit 5 (and assertj)

**Comment by phillip-kruger** [comment]
@t1 - There is some Conflicting files

**Comment by t1** [comment]
sorry... I just don't grok it :-/

**Pull request closed without merging**
