### PR TITLE
#400: Add support for GraphQL unions (1.6.x)

### PR DESCRIPTION
**Pull request by craig-day**
This ports #1469 to be against 1.6.x (javax)

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
LGTM ! Thanks for this @craig-day - this is awesome. I think we should be able to move this to the spec soon. Next step is to get this into a runtime like Quarkus. For Quarkus we might have to do some work to get the classes registered. Are you keen to look at this ? If so we can do a SmallRye release once this is merge and you can look at the Quarkus implementation ?

**Comment by phillip-kruger** [comment]
We would also need some documentation in the Quarkus Guide...

**Comment by phillip-kruger** [comment]
Ok v 1.6.1 is released (https://github.com/smallrye/smallrye-graphql/releases/tag/1.6.1) @craig-day are you keen to get this into Quarkus ? I can assist if needed

**Comment by craig-day** [comment]
@phillip-kruger I'll give it a shot today and see how it goes

**Pull request merged**
